# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Daniel Wells
tagline:          'DPhil Candidate in Genomic Medicine and Statistics'
description:      ''
url:              http://www.danielwells.me
baseurl:          /

author:
  name:           'Daniel Wells'
  url:            https://twitter.com/DanielJohnWells

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
